name: Android Build (assembleDebug)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android command-line tools and SDK packages
        run: |
          # use runner temp directory provided by the runner
          ANDROID_SDK_ROOT="$RUNNER_TEMP/android-sdk"
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools.zip
          mv cmdline-tools latest
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" --licenses || true
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-34" "build-tools;34.0.0"
        shell: bash

      - name: Grant execute for gradlew
        run: chmod +x ./gradlew

      - name: Build debug APK
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_HOME: $RUNNER_TEMP/android-sdk
          PATH: $PATH:$RUNNER_TEMP/android-sdk/platform-tools
        run: |
          # ensure Gradle uses the SDK installed in runner temp
          export ANDROID_SDK_ROOT="$RUNNER_TEMP/android-sdk"
          export ANDROID_HOME="$RUNNER_TEMP/android-sdk"
          export PATH="$PATH:$ANDROID_SDK_ROOT/platform-tools"
          ./gradlew assembleDebug --no-daemon -Pandroid.debug.obsoleteApi=true

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

